import { AlipayOption, GateWay, AlipayTradeSettleArgs, AlipayBillQueryArgs, AlipayPublicArgs, AlipayToaccountTransferArgs, AlipayTradeRefundArgs, AlipayTradeCloseArgs, AlipayQueryOrderArgs, AlipayCancelOrderArgs, AlipayCreateOrderArgs, AlipayTradePrecreateArgs, AlipayTradeRefundQueryArgs, ApiResponse, AlipayNotifyArgs, VerifyPamentArgs } from './config';
export default class Alipay {
    gateWay: GateWay;
    options: AlipayOption;
    constructor(options: AlipayOption);
    private normalizeOptions;
    readonly appId: string;
    readonly privKey: string;
    readonly publicKey: string;
    readonly notifyUrl: string;
    private validateBasicParams;
    private validateAPIParams;
    private validateParams;
    private makeResponse;
    private makeRequest;
    verifyPayment(params: VerifyPamentArgs): ApiResponse;
    makeNotifyResponse(params: AlipayNotifyArgs): ApiResponse;
    createWebOrderURL(apiParams: AlipayCreateOrderArgs, publicParams?: AlipayPublicArgs): ApiResponse;
    createPageOrderURL(apiParams: AlipayCreateOrderArgs, publicParams?: AlipayPublicArgs): ApiResponse;
    createPageOrder(apiParams: AlipayCreateOrderArgs, publicParams?: AlipayPublicArgs): ApiResponse;
    createWebOrder(apiParams: AlipayCreateOrderArgs, publicParams?: AlipayPublicArgs): ApiResponse;
    createOrder(apiParams: AlipayCreateOrderArgs, publicParams?: AlipayPublicArgs): ApiResponse;
    createAppOrder(apiParams: AlipayCreateOrderArgs, publicParams?: AlipayPublicArgs): ApiResponse;
    queryOrder(apiParams: AlipayQueryOrderArgs, publicParams?: AlipayPublicArgs): Promise<ApiResponse>;
    cancelOrder(apiParams: AlipayCancelOrderArgs, publicParams?: AlipayPublicArgs): Promise<ApiResponse>;
    tradeClose(apiParams: AlipayTradeCloseArgs, publicParams?: AlipayPublicArgs): Promise<ApiResponse>;
    tradeRefund(apiParams: AlipayTradeRefundArgs, publicParams?: AlipayPublicArgs): Promise<ApiResponse>;
    tradeRefundQuery(apiParams: AlipayTradeRefundQueryArgs, publicParams?: AlipayPublicArgs): Promise<ApiResponse>;
    billDownloadQuery(apiParams: AlipayBillQueryArgs, publicParams?: AlipayPublicArgs): Promise<ApiResponse>;
    tradePrecreate(apiParams: AlipayTradePrecreateArgs, publicParams?: AlipayPublicArgs): Promise<ApiResponse>;
    tradeSettle(apiParams: AlipayTradeSettleArgs, publicParams?: AlipayPublicArgs): Promise<ApiResponse>;
    toaccountTransfer(apiParams: AlipayToaccountTransferArgs, publicParams?: AlipayPublicArgs): Promise<ApiResponse>;
}
