import * as urllib from 'urllib';
import { AlipayOption, MethodType, AlipayResponse, AlipayTradeSettleArgs, AlipayBillQueryArgs, AlipayPublicArgs, AlipayToaccountTransferArgs, AlipayTradeRefundArgs, AlipayTradeCloseArgs, AlipayQueryOrderArgs, AlipayCancelOrderArgs, AlipayCreateOrderArgs, AlipayTradePrecreateArgs, AlipayTradeRefundQueryArgs, ApiResponse, AlipayNotifyArgs, VerifyPamentArgs, AlipayAPIArgs } from './config';
declare const _default: {
    new (options: AlipayOption): {
        gateWay: string;
        options: AlipayOption;
        normalizeOptions(options: AlipayOption): AlipayOption;
        readonly appId: string;
        readonly privKey: string;
        readonly publicKey: string;
        readonly notifyUrl: string;
        validateBasicParams(method: MethodType, publicParams: AlipayPublicArgs): AlipayPublicArgs;
        validateAPIParams(method: MethodType, options: AlipayAPIArgs): AlipayAPIArgs;
        validateParams(method: MethodType, apiParams: AlipayAPIArgs, publicParams: AlipayPublicArgs): AlipayPublicArgs;
        makeResponse(response: AlipayResponse): ApiResponse;
        makeRequest(params: AlipayPublicArgs, options?: urllib.RequestOptions): Promise<ApiResponse>;
        verifyPayment(params: VerifyPamentArgs): ApiResponse;
        makeNotifyResponse(params: AlipayNotifyArgs): ApiResponse;
        createWebOrderURL(apiParams: AlipayCreateOrderArgs, publicParams?: AlipayPublicArgs): ApiResponse;
        createPageOrderURL(apiParams: AlipayCreateOrderArgs, publicParams?: AlipayPublicArgs): ApiResponse;
        createPageOrder(apiParams: AlipayCreateOrderArgs, publicParams?: AlipayPublicArgs): ApiResponse;
        createWebOrder(apiParams: AlipayCreateOrderArgs, publicParams?: AlipayPublicArgs): ApiResponse;
        createOrder(apiParams: AlipayCreateOrderArgs, publicParams?: AlipayPublicArgs): ApiResponse;
        createAppOrder(apiParams: AlipayCreateOrderArgs, publicParams?: AlipayPublicArgs): ApiResponse;
        queryOrder(apiParams: AlipayQueryOrderArgs, publicParams?: AlipayPublicArgs): Promise<ApiResponse>;
        cancelOrder(apiParams: AlipayCancelOrderArgs, publicParams?: AlipayPublicArgs): Promise<ApiResponse>;
        tradeClose(apiParams: AlipayTradeCloseArgs, publicParams?: AlipayPublicArgs): Promise<ApiResponse>;
        tradeRefund(apiParams: AlipayTradeRefundArgs, publicParams?: AlipayPublicArgs): Promise<ApiResponse>;
        tradeRefundQuery(apiParams: AlipayTradeRefundQueryArgs, publicParams?: AlipayPublicArgs): Promise<ApiResponse>;
        billDownloadQuery(apiParams: AlipayBillQueryArgs, publicParams?: AlipayPublicArgs): Promise<ApiResponse>;
        tradePrecreate(apiParams: AlipayTradePrecreateArgs, publicParams?: AlipayPublicArgs): Promise<ApiResponse>;
        tradeSettle(apiParams: AlipayTradeSettleArgs, publicParams?: AlipayPublicArgs): Promise<ApiResponse>;
        toaccountTransfer(apiParams: AlipayToaccountTransferArgs, publicParams?: AlipayPublicArgs): Promise<ApiResponse>;
    };
};
export = _default;
