export declare const QUERY_ORDER = "alipay.trade.query";
export declare const CREATE_APP_ORDER = "alipay.trade.app.pay";
export declare const CREATE_WEB_ORDER = "alipay.trade.wap.pay";
export declare const CREATE_PAGE_ORDER = "alipay.trade.page.pay";
export declare const TRADE_CLOSE = "alipay.trade.close";
export declare const CANCEL_ORDER = "alipay.trade.cancel";
export declare const TRADE_REFUND = "alipay.trade.refund";
export declare const TRADE_SETTLE = "alipay.trade.order.settle";
export declare const TRADE_PRECREATE = "alipay.trade.precreate";
export declare const TRADE_REFUND_QUERY = "alipay.trade.fastpay.refund.query";
export declare const BILL_DOWNLOAD_QUERY = "alipay.data.dataservice.bill.downloadurl.query";
export declare const FUND_TRANS_TOACCOUNT_TRANSFER = "alipay.fund.trans.toaccount.transfer";
export declare const VERIFY_PAYMENT = "verify.payment.status";
export declare const NOTIFY_RESPONSE = "notify.response";
export declare const METHOD_TYPES: {
    QUERY_ORDER: string;
    CREATE_APP_ORDER: string;
    CREATE_WEB_ORDER: string;
    CREATE_PAGE_ORDER: string;
    CANCEL_ORDER: string;
    TRADE_CLOSE: string;
    TRADE_SETTLE: string;
    TRADE_REFUND: string;
    TRADE_PRECREATE: string;
    TRADE_REFUND_QUERY: string;
    BILL_DOWNLOAD_QUERY: string;
    FUND_TRANS_TOACCOUNT_TRANSFER: string;
    VERIFY_PAYMENT: string;
    NOTIFY_RESPONSE: string;
};
